### PR TITLE
Types 5.0

### PR DESCRIPTION
**Pull request by kuhar**

### CODE REVIEW

**Comment by agurfinkel** [comment]
@kuhar : is that intentional? You are proposing a PR from types branch that only includes commits from @caballa that seem fairly old

**Comment by caballa** [comment]
This code will just disable sea-dsa. I think his idea is just to have a version that compiles with llvm 5.0. I think it would be better to adapt crab-llvm with new sea-dsa. I'll try to do that.

**Comment by kuhar** [comment]
@agurfinkel I'm just created PRs for all the repositories that would need to be updated if we merged the sea-dsa with types into the development branch.

**Comment by kuhar** [comment]
@caballa why were these parts of the codebase disabled here?

**Comment by agurfinkel** [comment]
@kuhar I this was to avoid updating crab while sea-dsa is evolving

**Comment by caballa** [comment]
The code about sea-dsa in crab-llvm didn't not compile with `types-5.0`. I just commented all the sea-dsa functionality in crab-llvm so that seahorn branch with types-5.0 did not complain. As I said, the solution is to modify the code to take into account the new API changes in sea-dsa

**Comment by kuhar** [comment]
Do you want me to look into it, @caballa?

**Comment by caballa** [comment]
It should be straightforward. If you have time it would be great.

**Pull request closed without merging**
